name: foopes
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # SDK
  flutter:
    sdk: flutter

  # FRONT
  cupertino_icons: ^0.1.3
  flare_splash_screen: ^3.0.1
  flutter_launcher_icons: ^0.7.5
  flutter_inner_drawer: ^0.5.6+1

  # BACK
  bloc_pattern: ^2.5.1
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  flutter_advanced_networkimage: ^0.7.0
  one_context: ^0.4.0
  path_provider: ^1.6.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/logo/
    - lib/assets/imagens/

flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/logo/logo.jpg'